version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: dairy_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dairy_db
      MYSQL_USER: dairy_user
      MYSQL_PASSWORD: dairy_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: dairy_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
